apiVersion: v1
kind: Pod
metadata:
  name: development-box
spec:
  containers:
  - name: development-box
    image: sanjayrancher/development-box:v0.0
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: Always
    env:
    - name: NATS_SERVER_URL
      value: "nats://nats_client:VfU6TcAl9x@nats-client.default.svc:4222"
    - name: ES_ENDPOINT
      value: "https://opendistro-es-client-service.default.svc.cluster.local:9200"
    - name: FAIL_KEYWORDS
      value: "fail,error,missing,unable"
    - name: MINIO_SERVER_URL
      value: "http://minio.default.svc.cluster.local:9000"
    - name: MINIO_ACCESS_KEY
      value: "myaccesskey"
    - name: MINIO_SECRET_KEY
      value: "mysecretkey"
    - name: ES_USERNAME
      value: "admin"
    - name: ES_PASSWORD
      value: "admin"
    - name: ES_USER
      value: "admin"

